apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appointment
  template:
    metadata:
      labels:
        app: appointment
    spec:
      containers:
      - name: appointment
        image: 543003945919.dkr.ecr.eu-north-1.amazonaws.com/satishrepo:appointment-service
        ports:
        - containerPort: 3001

